### ISSUE TITLE
Typo and wrong slash being used in zip file, not corresponding with audacity's folders

### ISSUE THREAD

**Issue by Penticton** [visoart/audacity-themes#1]
Sys Specs at bottom....
          
Your instruction at https://visoart.github.io/audacity-themes/  for Windows is to put themes into the following directory  %appdata%/audacity/Theme  which is indeed correct, but inside the  audacity-themes-master.zip  file I got from the GitHub site here THEME folder that should be inside isn't, and it's actually  %appdata%/audacity/**THEMES** with the letter "S" at the end which unzips to the completely wrong spot for the program to find it, at least I certainly think it would?

Also, you're using the wrong slash in the https://visoart.github.io/audacity-themes/   page's instructions for Windows.    It's typed out as   %appdata%/audacity/Theme  and when I put that in Windows Explorer to navigate there it won't go, same thing for extracting it to there, but if you change it to  %appdata%\audacity\Theme  it properly navigates there and finds one's C:\Users\%username&\AppData\Roaming\audacity  .

Did I get this just completely incorrect? Am I right about anything here? I've lost complete concentration with my PC tonight for some reason, I'm sorry, I think at least you'll find some of what I said is an issue that needs fixing.
So, you have my most heartfelt apologies and deepest regrets, I know I probably just need some food, and that's coming in 14 mins from the oven.

Specs:
Firefox 90.0.2 64-bit
Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
System Model: X541UAK        <-------- This is incorrectly reporting X541UAK
BIOS: X541UAK.308 (type: UEFI)

And I have the Asus Model Number of X541UA.  and that's it, that's my model number taken right off the box, now i think, by looking at the specs above and the following image, i have successfully flashed the INCORRECT Bios version?
Is there anyone here that can assist me in getting it back to where it belongs, with it's X541UA version, I believe it's Ver .307.
I'm fairly well versed at anything Windows 10 Pro and I can follow along without issue no problem.

![20210712_152447RESIZED](https://user-images.githubusercontent.com/18225108/127267588-8acddb1a-574d-491c-8ed8-f343df682d0c.jpg)

Thanks a whole bunch!
(P.S. I use and found github in the first place by downloading modules for my rooted Samsung, which I still do, with Magisk and EdXposed etc etc.)

Daniel.

**Comment by visoart** [comment]
Hello Daniel! Thank you for your ticket!

I have tested all of your above points. On my machines I put the theme image to `%appdata%/audacity/Theme` and it works. I believe my folder is correct as my custom theme works in Audacity. The same thing goes with your second point - my Windows machines easily navigate to the directory when I put `%appdata%/audacity/Theme` into the adress bar in Explorer. I'll update instructions on the website and blog just for the sake of Windows being sensitive on slash and backslash. I use Windows10.

Thanks for your report. ♥
